// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoJfYqbEnFnQ_dq-NpoAQRatejaOl7GXc',
    appId: '1:111954636874:web:fce3e13bccdb9f022cb6b3',
    messagingSenderId: '111954636874',
    projectId: 'dulcehora',
    authDomain: 'dulcehora.firebaseapp.com',
    storageBucket: 'dulcehora.firebasestorage.app',
    measurementId: 'G-FKHFJ8TG01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm7EGm_5MQY6oLU0nlTX8NpfSCwps7J0A',
    appId: '1:111954636874:android:f3b9a49ffdb4e29c2cb6b3',
    messagingSenderId: '111954636874',
    projectId: 'dulcehora',
    storageBucket: 'dulcehora.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo8attXh_IjvxBO6zzECiVyUHy9p8GBCs',
    appId: '1:111954636874:ios:6ec50632bc055c2f2cb6b3',
    messagingSenderId: '111954636874',
    projectId: 'dulcehora',
    storageBucket: 'dulcehora.firebasestorage.app',
    iosBundleId: 'com.example.dulcehora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo8attXh_IjvxBO6zzECiVyUHy9p8GBCs',
    appId: '1:111954636874:ios:6ec50632bc055c2f2cb6b3',
    messagingSenderId: '111954636874',
    projectId: 'dulcehora',
    storageBucket: 'dulcehora.firebasestorage.app',
    iosBundleId: 'com.example.dulcehora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoJfYqbEnFnQ_dq-NpoAQRatejaOl7GXc',
    appId: '1:111954636874:web:47da33980599647d2cb6b3',
    messagingSenderId: '111954636874',
    projectId: 'dulcehora',
    authDomain: 'dulcehora.firebaseapp.com',
    storageBucket: 'dulcehora.firebasestorage.app',
    measurementId: 'G-N1JWT7Z0DH',
  );
}
